language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
install: pip install .
script: nosetests
notifications:
    webhooks:
        - http://moriarty.thesharp.org:5000/travis/2c27baee8754c01522cf751c1ed393b1/
